import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Footer from "@/common/Footer";
import { Toaster } from "react-hot-toast";
import { ReactQueryProvider } from "./ReactQueryProvider";
import AuthContextProvider from "@/context/AuthContext";
import {
  getCertificates,
  getTrainigFormats,
  getTrainingVenues,
  getTrainings,
} from "@/services/user";
import NavBar from "@/common/NavBarComponents/NavBar";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const RootLayout = async ({ children }: { children: React.ReactNode }) => {
  const formats = await getTrainigFormats();
  const venues = await getTrainingVenues();
  const certificates = await getCertificates();
  const categories = await getTrainings();
  return (
    <html lang="en" className="scroll-smooth">
      <body className={inter.className}>
        <ReactQueryProvider>
          <AuthContextProvider>
            <Toaster />
            <NavBar
              formats={formats}
              venues={venues}
              certificates={certificates}
              categories={categories}
            />
            {children}
            <Footer />
          </AuthContextProvider>
        </ReactQueryProvider>
      </body>
    </html>
  );
};
export default RootLayout;
